/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/app.customers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/tickets': typeof AppTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/tickets': typeof AppTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/tickets': typeof AppTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/packages'
    | '/app/profile'
    | '/app/subscriptions'
    | '/app/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/packages'
    | '/app/profile'
    | '/app/subscriptions'
    | '/app/tickets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/packages'
    | '/app/profile'
    | '/app/subscriptions'
    | '/app/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppTicketsRoute: typeof AppTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppTicketsRoute: AppTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
